---
title: "Class work"
author: "Samuel"
date: "2023-11-28"
output: html_document
---

let's put this up to github

```{r}
library(tidyverse)
library(dplyr)
```

```{r}
gdp <- read.delim("../data/oecd-gdp.csv")
gdp %>%
  head()
```

##
```{r}
gdplong <- 
  gdp %>%
  pivot_longer(!c(country, indicator))
gdplong %>%
  head(10)
```

##
```{r}
gdpLong <-
  gdp %>%
  pivot_longer(!c(country, indicator),
           	names_to = "year",
           	values_to = "gdp")
gdpLong %>%
  head(10)

```

##
```{r}
gdpLong <-
  gdp %>%
  pivot_longer(!c(country, indicator),
           	names_to = "year",
           	values_to = "gdp") %>%
  mutate(year = as.numeric(year))
gdpLong %>%
  head(10)

```

##
```{r}
p <- data.frame(pregnant = c("Yes", "No"),
            	male = c(NA, 25),
            	female = c(11, 18))
p

```

##
```{r}
pl <- p %>%
  pivot_longer(c(male, female),
           	names_to = "sex",
           	values_to = "count")
pl

```

##
```{r}
pl %>%
  pivot_wider(id_cols = pregnant,
          	names_from = sex,
          	values_from = count)
```


